#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only)

echo "Staged files: $STAGED_FILES"

ROOT_DIR=$(pwd)

cd "$(git rev-parse --show-toplevel)"

BRANCH=$(git symbolic-ref --short HEAD)

echo "Running Husky..."
nx reset && nx affected:lint --base=$BRANCH && nx affected:test --base=$BRANCH && nx affected:e2e --base=$BRANCH